# permissions for end users to edit democontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: democontroller-editor-role
rules:
- apiGroups:
  - groupcontroller.hub.docker.com
  resources:
  - democontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - groupcontroller.hub.docker.com
  resources:
  - democontrollers/status
  verbs:
  - get
