# permissions for end users to view democontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: democontroller-viewer-role
rules:
- apiGroups:
  - groupcontroller.hub.docker.com
  resources:
  - democontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - groupcontroller.hub.docker.com
  resources:
  - democontrollers/status
  verbs:
  - get
